### ISSUE TITLE
CSS Styling breaks Meta Keys field

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#101]
[https://github.com/nilshoerrmann/subsectionmanager/blob/merging/assets/subsection.publish.css#L41-43](Line 41 - 43) of the Subsection Manager CSS file applys a 100% width to all input elements.

This causes the Meta Keys styling to break as the input's explode out the frame. Removing this line doesn't seem to change any of the appearance of the other fields, but it fixes the issue.

I am using the SSM 1.2 beta on Firefox 4

(As a sidenote [https://github.com/nilshoerrmann/subsectionmanager/blob/merging/assets/subsection.publish.css#L23-24](There is some invalid CSS also)

**Comment by nilshoerrmann** [comment]
Hm, I'm not sure if I should add specific styles to this extension or leave the fix to Meta Keys. My policy until know was to only support the core fields by default (just because I cannot support all extensions by default). 

Regarding the sidenote: This seems to be related to the last merging. Thanks for pointing it out!

**Comment by brendo** [comment]
I'm not proposing adding any styles, rather dropping that rule.

The presence of it doesn't seem to affect any field, core or not.

**Comment by nilshoerrmann** [comment]
Sorry, I misread that. I remember that the 100% were important to fix some styling issues. Maybe this is no longer valid with the core style updates in version 2.2. I'll have a look at it.
