### ISSUE TITLE
Tabs: height does not automatically resize

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#104]
When opening a Subsection Manager included in Subsection Tabs, the tab height does not automatically resize to show the full content. So far, a scrollbar appears -- which is okay (as everything stays usable), but resizing would be nicer.

**Comment by nilshoerrmann** [comment]
This issue is also valid for all instances of Stage inside a Subsection Manager.

It's a tricky problem that cannot be solved easily. I tried to automatically resize the `iframe` in the `iframe` branch, but the resizing is delayed (which is okay but not beautiful) and Firefox suffers a few severe focus issues (it flickers because it cannot decide whether to focus the `iframe` or the parent frame).

**Comment by nilshoerrmann** [comment]
This should be fixed now.
