### ISSUE TITLE
Redeclare Stage

### ISSUE THREAD

**Issue by designermonkey** [symphonists/subsectionmanager#116]
When using the new Date Time experimental branch, an error is being thrown that the SSM is trying to redeclare the Stage Class.

**Comment by designermonkey** [comment]
Fixed this by copying your test for the class from datetime. Sending a pull request.

**Comment by nilshoerrmann** [comment]
Please update SSM to the `merging` branch (recommended / version 1.2 beta) or - if you like adventures - switch to the `tabs` branch. That should fix the issue.

**Comment by designermonkey** [comment]
tabs is too much magical for me right now ;)

**Comment by nilshoerrmann** [comment]
Oh, it's working quite well. No wizards needed :)

**Comment by designermonkey** [comment]
I may take a look soon then!

PS, I can't merge with `merging` branch as the `master` and `merging` branches are totally different. I did the change on master by accident, and now I'm confused as to where to fix this.

As it's a simple fix, from `master` to `master` can it just be pulled straight in?

**Comment by nilshoerrmann** [comment]
Ah sorry, that's due to the Stage submodule: while the `master` branch bundles Stage directly, the `merging` branch contains a submodule. The easiest way is to switch branches (don't try to merge both branches). `merging` is more stable than `master`.

You have to force the checkout of the `merging` branch and than pull the Stage submodule: 

```
$ git checkout -f merging
```

**Comment by designermonkey** [comment]
Ah, your `merging` branch has this fix in it already it seems...
