### ISSUE TITLE
DatasourceEntriesBuilt delegate

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#135]
Following on from #132, (paraphrased)

> Something that is probably of more concern is that this function runs on every Datasource, regardless of if a SSM is involved or not, which creates an overhead for every datasource of the entire site.

You are right. I think SubsectionManager should parse fields and cache data when Data Source is saved (i think there is delegate for that, right?), and then just load cache when Data Source calls DataSourceEntriesBuilt.

Though it probably is not about 2-3 queries penalty anymore. Since it does not try to handle "regular" fields that are not part of subsection anymore, there should be not much slow down.

We just need to make SSM know which Data Source contains fields that SSM should handle, so it will not try to check all fields of every Data Source. I was thinking about parsing field data when Data Source is saved, but if any field would change after that, SSM would not know that.

**Comment by ahwayakchih** [comment]
https://github.com/nilshoerrmann/subsectionmanager/commit/6edc73d8b22885d217989e973e67d5c855739427

**Comment by ahwayakchih** [comment]
Please test, and let me know if it works better with change linked above.
It should work a lot faster now, even for Data Sources that do get data from SSM fields.

**Comment by nilshoerrmann** [comment]
I noticed a problem with this new concept and it took me a while to figure out the causes:

If you manually change the included fields of a Data Source containing a SSM field, nothing changes on the frontend because the cache is not refreshed. It's also a problem when you have your workspace in a separate repository and someone else pushes changes to a Data Source file: although you pulled and updated the file correctly on your end, the output will be wrong.

Would it be possible to take the time into account when the Data Source file has last been changed and not just rely on the backend delegates?
