### ISSUE TITLE
Revise interface for quantities

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#138]

**Comment by nilshoerrmann** [comment]
@ahwayakchih: What about something like this?

![Quantities](http://projekte.nilshoerrmann.de/screenshots/sym_quantities.png)

**Comment by ahwayakchih** [comment]
Yes, i was thinking about using "x" too (i like the "x" version more than "|" version). It looks good - i like the idea. But i was worried about drag & drop. Since quantity is an input field, user would have to click somewhere else to drag & drop item. Another thing is that it will "break" visual "columns" when one SSM field will be used without quantities and other will be used with quantities, i.e., one will have item titles and photos at the leftmost side of an item, other one will have them closer to the center of an item. Would that be OK, or would it annoy users?

**Comment by nilshoerrmann** [comment]
For your information: 
- [Discontinuing Support for Subsection Manager](http://getsymphony.com/discuss/thread/83270/7/#position-121)
- [Investigating Relationships](http://getsymphony.com/discuss/thread/96191/)
