### ISSUE TITLE
Updating and Sorting

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#142]
Although I thought yesterday that @ahwayakchih updates to the sorting logic worked, it seems like the updater is messing up things and attaches non existing items. It's a bit strange.

This definitely need some more tests.

**Comment by nilshoerrmann** [comment]
Looking deeper into this, it seems that the updater has deleted at least on subsection item while still referencing it in the database.

**Comment by ahwayakchih** [comment]
It does not delete any entries. It simply copies selected items to temporary table, and then back, in selected order, to "real" table. It should not drop any selected items, but there may be a bug. Can You tell if dropped item was sorted or not?

It may add items, that were sorted before and dropped later (because they were kept in sortorder). I can make them dropped by updater.

**Comment by nilshoerrmann** [comment]
Good question. I think the item was sorted.

Maybe it would be good idea to make the sorting updater an optional feature that does not run automatically?

**Comment by ahwayakchih** [comment]
Maybe, but then all items would end up unsorted after update.

But it could be a good idea to make it separate form udpate function anyway, because with large enough data sets and number of fields it may hit timeout.

**Comment by nilshoerrmann** [comment]
> Maybe, but then all items would end up unsorted after update.

Yes, but we are talking about a major update to this extension so I think it's okay if it involves an extra step.

**Comment by ahwayakchih** [comment]
OK. So update function could set some session cookie, and then SSM could add message with link to "data conversion" page. We could put both sortorder and data source conversion functions there.

**Comment by nilshoerrmann** [comment]
That sounds good!

**Comment by ahwayakchih** [comment]
OK, i will work on this :).

**Comment by nilshoerrmann** [comment]
Perfect!

**Comment by ahwayakchih** [comment]
> Good question. I think the item was sorted.

I think i found a reason:
https://github.com/nilshoerrmann/subsectionmanager/commit/ebc8798cad5f65e02e1e6b3b9f0bc3053165c470

Could You test it again? Data in stage sort table is still there, so just forcing update to be run again should do.

`context` should not matter in theory, because there should be one context per field, but maybe there was some other one there and screwed up things for updater.

**Comment by nilshoerrmann** [comment]
I will.

**Comment by nilshoerrmann** [comment]
It seems to work so far.

**Comment by nilshoerrmann** [comment]
But still, I'm dealing with a site that is not doing much sorting.

**Comment by ahwayakchih** [comment]
I think that separated updater will run additional testing. Maybe simple entry counting pre and post, or comparing which entries are missing that were selected. That will allow user to test before saving changes and testing 2.x will be safer.

**Comment by ahwayakchih** [comment]
Thanks for testing :).

**Comment by ahwayakchih** [comment]
I was wrong: it will not select entries that were selected, then deselected later and just left out in sortorder table.
