### ISSUE TITLE
Offer specific fields, such as "Image Manager"

### ISSUE THREAD

**Issue by tachyondecay** [symphonists/subsectionmanager#145]
I've been thinking about the comments in the "List of wanted extensions" thread about the need for a robust image/document manager in Symphony, particularly [Nils' remark](http://symphony-cms.com/discuss/thread/70339/4/#position-62) that Subsection Manager doesn't try to cover every possible use case, but owing to Subsection Manager's flexibility, users often try to cover more use cases than it can comfortably serve.

One of the reasons for this well-intentioned abuse of Subsection Manager on the user's side is probably its panoply of interface options: the subsection manager field in the section editor _looks_ like it can do anything. Moreover, it has so many options that the number of combinations is quickly overwhelming. This makes it difficult for us as developers to maintain and improve the interface, because we keep having to think about how different combinations might break the interface. This makes it difficult for users, because they often have more options than they need if _all_ they want is a drag-and-drop image selector.

My suggestion is that we have Subsection Manager offer pre-defined fields with more specific and limited functionality. So, for example, we could offer an "Image Manager" for people looking to drop images, and an "Attachment Manager" for people who want to attach downloadable files. We'd also keep the current vanilla subsection manager for power users who really need to roll their own subsections. In most cases, however, one of our pre-defined fields is probably going to work just fine.

Now, this could quickly get complicated and more difficult to maintain, and I'm not suggesting we try to cover too many use cases like this. I think we can hit some of the most common ones, where users need something more well-defined than the vanilla subsection manager field offers. One thing we would have to discuss is whether we can keep the internal storage identical across the fields (making them essentially different interfaces for Subsection Manager), which seems like less work for us, or tweak the storage for each of the fields to make Subsection Manager more efficient.

**Comment by ahwayakchih** [comment]
It could be useful, but i really dislike hundreds of field types for basically the same task (like upload fields - tiny little change and already a separate field). If field type could be changed without losing data or having to run custom SQL to convert data, then it would be ok. But for now, fields types are too "static".
Maybe it would be better to create different JavaScript interfaces? Field and HTML could stay the same, just different JS could be used. A bit like with `Textarea` fields and selecting `Text Formatter`.

**Comment by tachyondecay** [comment]
I feel the same pain, Marcin. I love the clever new abilities extensions gives me but groan whenever they involve a new field type. This should not be as much of a problem in this case, especially if we don't differentiate among fields in the internal storage.

> Maybe it would be better to create different JavaScript interfaces? Field and HTML could stay the same, just different JS could be used. 

Now you have me wondering if my original proposal is overkill. I was envisioning people selecting different fields, like `Subsection: Images` and `Subsection: Default`. Now I'm wondering if we even need to tell Symphony the difference. To Symphony, as to our internal storage, it could all be "Subsection Manager." Then we could load the appropriate interface on the fly. However, if we are going to the trouble of creating different interfaces, I feel like we might as well have our field load different HTML _and_ JavaScript instead of just different JavaScript.

I'm biased, because I am not great with JavaScript, so I tend to consider other solutions first. But I'm willing to be persuaded. ;)

**Comment by ahwayakchih** [comment]
I guess we could output different administration HTML for different "modes" (not modes used in Data Sources, just different modes of field interface :). Thing is that HTML that is generated now (at least in 2.x) is already pretty generic. Most of the work is done by stage's JavaScript. So if we could allow developer to select something else instead of stage, to manage entries, it should be enough.

Another thing i was also thinking about is implementing "override" feature, to generate HTML through regular Symphony pages (i mean, special page, created by developer). I already am doing something like that in my [Autocompleter](https://github.com/ahwayakchih/autocompleter) extension. Search results are downloaded from Symphony page, so developers can filter entries and output them whichever way they want (there are just a few "must haves" there, like specific CSS class of each item).
That would not only allow to create interfaces perfectly suited for specific case, but also generate custom drop text values (even changed depending on time of the day - maybe stupid example, but shows how much flexibility such feature could add :).

**Comment by nilshoerrmann** [comment]
I have been thinking a lot about a simple and and advanced mode for the Subsection Manager settings but I never came up with a working solution. The mass of settings and possibilities is a real problem of this extension. The extension promisses a lot but cannot handle all setups possible equally well. 

Maybe this could lead to a radical change: As of Subsection Manager 2, this extension could only provide the internal logic to manage subsections (storing items, data source output, event handling). Everything could be focussed on data management and performance. Make it fast and reliable.

At the same time we could source out the interface into other extensions. It would – for example – be possible [to create a separate extension offering the Stage interface](http://symphony-cms.com/discuss/thread/72244/) which could either be detected by Subsection Manager and offered as an UI setting or which could just offer it's own field extending `field.subsectionmanager.php`. I'm not sure which would be best – the first solution would make Stage sharing easier (which is also used by Date and Time), the second opens other possibilities: it would – for example – be possible to have extensions just extending `field.subsectionmanager.php` by adding a settings array to tweak the field settings panel. This way it would be simple to create a specialised Image Manager based on this extension.

**Comment by ahwayakchih** [comment]
I really dislike the idea of building new field types on top of SubsectionManager fields. Unless some core stuff is being modified/changed, small changes should be added through JavaScript and additional extensions (but not fields, only something that manages its own database tables).
Field types are too hard to change once site goes online, so it is better to keep field type unchanged, and just modify its function with options.

**Comment by tachyondecay** [comment]
> ... the second opens other possibilities: it would – for example – be possible to have extensions just extending `field.subsectionmanager.php` by adding a settings array to tweak the field settings panel. This way it would be simple to create a specialised Image Manager based on this extension.

I think this idea is really cool, because it lets other developers create the subsection-like fields they need without having to come up with the internal logic all over again.

> I really dislike the idea of building new field types on top of SubsectionManager fields.... Field types are too hard to change once site goes online, so it is better to keep field type unchanged, and just modify its function with options.

But what if we come up with a way for Symphony to view the extended field types others create _as_ Subsection Manager fields? Then Symphony won't care as long as one is changing between two Subsection Manager fields, but it will make extending the field easier.

So we'll can have a single "Subsection Manager" field that one adds to a section, and then an additional option in the configuration of that field that lets one select the "type" of subsection one wants. This type will itself be an extended `field.subsectionmanager.php`, but Symphony won't see this as a distinct field from the original `field.subsectionmanager.php`. Since the internal storage will be the same, neither will Subsection Manager.

I admit I haven't worked with fields in Symphony, so this might end up being a lot more difficult than the way you're proposing we do it, Marcin. And I could be seriously breaking some Symphony logic here. :D But I'm just brainstorming some ideas so we can see all of our options.

**Comment by ahwayakchih** [comment]
In Symphony new field type is a new PHP class. Symphony remembers which one was added. To switch type, one has to remove field and add new one (or call risky SQL queries manually, but... what if other field/extension caches settings of SSM somewhere? One would have to know every extension's code to be sure nothing gets screwed).

In theory, we could make SubsectionManager field load optionally selected field class, and pass function calls to it, but i do not think that is a clean solution.

What you want by specialized image or video, with "data" handled by SubsectionManager field, is just a change in the interface. Maybe with additional or changed field options. I think that such "cosmetic" changes should not be implemented through new fields (PHP classes) that extend original field. They do not require huge changes (like different way of storing data in database) and could modify interface and/or field options through JavaScript (or maybe SSM could create own delegate calls?).

If we create some kind of example or "template" (maybe specialized "subsection images") that does change stuff, without a need to create whole new type of  field, then other developers could create own versions just by copying it and modifying (so the same way they create new field types now - by copying field base class, or some other similar field type class).

> and then an additional option in the configuration of that field that lets one select the "type" of subsection one wants.

That is exactly what i am writing about. I just called it "mode", because field "type" is not easy to change in Symphony. It may be "interface type", or "subsection data type" (image, video, etc...). Anyway, it would change interface of field settings (different and/or added options) and field shown on entry edit page (something else used instead of stage).

**Comment by ahwayakchih** [comment]
If you can, check how we implemented additional functionality to SSM field in [Bulk Importer](https://github.com/brendo/bulkimporter). It changes "create" button ([info](https://github.com/brendo/bulkimporter/issues/8) or [screenshot](https://github.com/ahwayakchih/bulkimporter/raw/screenshots/screenshots/BulkImporterAndSubsectionManager.png)), and adds options to SSM field settings. It is a small change (compared to changing stage for something else), but the same way could be used for bigger changes too.

This way allows developer to use different extension or interface later by simply changing option of SSM field, instead of removing field and adding new field to section.

**Comment by nilshoerrmann** [comment]
For reference: https://github.com/symphonists/relationsfield/issues/1
