### ISSUE TITLE
Empty name causes SMM to only display the latest entry

### ISSUE THREAD

**Issue by kanduvisla** [symphonists/subsectionmanager#155]
I have a section called Media with the fields 'description' and 'file'.

'Description' is not required, so this can be empty (or displayed as 'None' in Symphony).

Now when I create several new items in SMM, and give none of them a description, it saves correctly. But... as you can see immeaditatly when the page reloads, the SMM itself only shows the latest item. Therefore clicking on 'Save Changes' again will result in only saving one entry instead of them all

**Comment by klaftertief** [comment]
I experienced this some days ago as well. I think this is caused by [this line](https://github.com/nilshoerrmann/subsectionmanager/blob/master/lib/class.subsectionmanager.php#L256) in `class.subsectionmanager.php`:

```
$html[strip_tags($tmp)] = str_replace(' data-drop=""', '', $tmp);
```

`strip_tags($tmp)` can be the same for different SSM items, like in your case. Then every new item overrides the previous ones, resulting in only showin the last one. So

```
$html[] = str_replace(' data-drop=""', '', $tmp);
```

should work. But there might be side effects.

**Comment by ahwayakchih** [comment]
@klaftertief, good point. But that would remove sorting by caption.

@kanduvisla, can you write which verison of SubsectionManager are you using and what caption is set for the SSM field?

**Comment by kanduvisla** [comment]
Im using version 1.2 (the master branch)

The caption I use is: `{$description}`, so yes, when $description is empty then every new item overrides the previous ones.

**Comment by ahwayakchih** [comment]
OK, so try to change the line **klaftertief** mentioned to something like this:

```
$html[strip_tags($tmp).'-'.$entry['id']] = str_replace(' data-drop=""', '', $tmp);
```

That should keep all items, but items with empty description will be sorted before those with non-empty description.
