### ISSUE TITLE
support html5 drag and drop files

### ISSUE THREAD

**Issue by JiriVM** [symphonists/subsectionmanager#165]
Would it be possible to  support html5 drag and drop, so you can drop a picture from your desktop into the manager, and it creates a new entry for that picture in the picture section and associates it with the entry you are on?

**Comment by nilshoerrmann** [comment]
It would certainly be possible but it's quite difficult to create a proper item based on a dropped file because you are free to setup your subsection the way you want.

It's a complicated nice-to-have that not planned at the moment.

Maybe an drag and drop upload field might be a first step – but in this case we'd talk about a new extension.
