### ISSUE TITLE
Clicking on Subsection Entry Text opens Image in Subsection

### ISSUE THREAD

**Issue by animaux** [symphonists/subsectionmanager#222]

**Comment by nilshoerrmann** [comment]
This issue occurs due to the switch from Stage to Duplicators. The expected behaviour would be to just prevent the default behaviour so the the link can only be accessed via the context menu.

**Comment by animaux** [comment]
I’d agree, in my local copy I removed the link as a workaround anyway :)

**Comment by nilshoerrmann** [comment]
Actually, I don't mind. We could just remove it.
Alexander, what about sending your workaround in a pull request to the `development` branch?

**Comment by animaux** [comment]
I have only removed the wrapping links themselves. Is there not any .js stuff connected that should be removed as well?

**Comment by nilshoerrmann** [comment]
No. If there was JS stuff around, you would never have noticed this bug :)

**Comment by animaux** [comment]
Ok, willco!

**Comment by andrewminton** [comment]
Has this change/suggestion been implemented to the latest release at all? I've only just discovered this via a clients frustration. Long names of files means that the link expands quite wide along the entry of the subsection and forces a click. Because this opens in same window all edits or creation steps in the entry with a subsection after a click are lost :( boo. 

Simple fix really, so I would vote for removal as well if that was cool. In the context of the entry we dont't need access to the link at all here.

**Comment by nilshoerrmann** [comment]
The link should be there so you are able to access the original file with a right click. The JavaScript should only prevent the default behaviour on left click.

And no, this has not been fixed yet.

**Comment by andrewminton** [comment]
Ah ok, thanks for update.. what JS file would I need to locate the code to disable it for the time being? thanks.

**Comment by nilshoerrmann** [comment]
Oh, I just noticed that the `development` branch includes Alexander's fix. It's not the final fix, but it works in your case.

**Comment by andrewminton** [comment]
Woop, cool beans. I shall take a look in there. Thanks.
