### ISSUE TITLE
Firing search only if searched string is greather than one

### ISSUE THREAD

**Issue by mblabs** [symphonists/subsectionmanager#229]
Starting from the closed issue https://github.com/hananils/subsectionmanager/issues/204

In SSM 3 There is a way to fire the search only if the searched string is greather than one or more characters? This because, when the subsection contains many items, the browser crashes.

**Comment by g-wilson** [comment]
+1 for this. Having the same issue with 1000+ entries, even on a high end pc the browser can't handle it.

I've had a look and it is a harder issue that it first seems. The thing that causes the browser hang/crash is loading the results into the DOM, not the actual loading of the data. SSM doesn't actually query the database for what you type, so it loads every result and then filters with jQuery (as I understand it) so at some point the browser has to load all the items.

A fix would be to re-write the filtering so that it loads the returned items as an array that can be manipulated in javascript before inserted into the DOM. At the moment the query returns the html directly, and then the html is inserted into the document, and then filtered. Better still would be to query the database after 1 or more characters in the string for that string rather than all entries, but I don't know if this is feasible.

**Comment by nilshoerrmann** [comment]
For your information: 
- [Discontinuing Support for Subsection Manager](http://getsymphony.com/discuss/thread/83270/7/#position-121)
- [Investigating Relationships](http://getsymphony.com/discuss/thread/96191/)
