### ISSUE TITLE
Keyboard input a bit weird

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#59]
From the Symphony [extension issue tracker](http://symphony-cms.com/download/extensions/issues/view/41121/9/):

> I’m getting a couple of issues to do with keyboard interaction with the Subsection manager. They are:
> 
> In Safari the “Enter/Return” key is hijacked so submitting the form from anywhere will open a “Create new” item in the subsection manager
> If you tab into the search field, the search doesn’t work. If you focus it with the mouse at any point (and they say tab back in) it does work.
> Tabbing out of the search field doesn’t close the selector
> And one suggestion:
> 
> Pressing “ESC” should close the selector and clear the search field if the selector if open
> Not sure if you want those as separate issues. Let me know if you want me to submit them separately.

**Comment by nilshoerrmann** [comment]
The return bug should be fixed for version 1.0 the other keyboard related features should be added in 1.1.

**Comment by nilshoerrmann** [comment]
Does anyone understand this "Enter/Return" key issue? For some reason the click event for the `Create New` button is triggered when hitting the enter key. It doesn't make sense to me why this is happening. This (quite essential) line is causing the trouble:

```
object.find('.create').live('click', create);
```

Any ideas?

**Comment by simoneeconomo** [comment]
I'm not able to reproduce that on Google Chrome, so it doesn't seem to be a bug strictly related to WebKit (at least not the branch being used by Google Chrome).

**Comment by nickdunn** [comment]
I discovered this today and was about to log it as a bug, but found it had already been raised. My own bug report:

---
- create a child section with a single Text Input field
- create a parent section with a single Text Input field and a Subsection Manager linking to the child section
- leave the Subsection Manager as optional (not required)
- create a new entry in the parent field: while the Text Input field (not the one in the Subsection Manager) has focus, hit Enter to submit the form

Expected behaviour: the entry form submits and the new entry is created
Actual behaviour: the Subsection Manager opens and gives focus to the Text Input within

---

This is replicable in Firefox 3/Mac.

My guess is that hitting Enter submits the form using the first input[button/submit] that it finds. Since the "Create New" button is higher in the source order than Symphony's "Create Entry" button, it receives focus first.

**Comment by nilshoerrmann** [comment]
Nick, do you have any idea how to fix this? I haven't been able to find a solution yet. You are certainly right about the button order but how could the click event for the Subsection Manager be adjusted to not fire in the described circustances?

**Comment by nickdunn** [comment]
The HTML4 spec doesn't specify. The HTML5 spec [however does](http://www.w3.org/TR/html5/association-of-controls-and-forms.html#default-button).

> agents may establish a button in each form as being the form's default button. This should be the first submit button in tree order

and

> if the default button is disabled, the form is not submitted when such an implicit submission mechanism is used

I had hoped that by adding "disabled" to the Subsection Manager's button the browser might skip it. Didn't work.

I read in a few sources that Webkit/Gecko would choose the button with the largest tabindex, but when I tried this in Firefox 3 and Safari 5 it did not work.

So it seems as if the only solution is for Subsection Manager to add an event listener for the Enter key (when a input or select has focus, but not textarea!) and should cancel the default form action and mimic a click on the submit button.

**Comment by nilshoerrmann** [comment]
This issues will be fixed in the next update of this extensions. The button has been replaced by an anchor.
